server: 
  port: 8666

spring: 
   application: 
     name: configcenter
   cloud: 
     config: 
       server: 
         git: 
           uri: https://github.com/michangwei/configcenter.git
   